# Generated by Django 5.1.1 on 2024-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.PositiveSmallIntegerField()),
                ('farmer_name', models.CharField(max_length=20)),
                ('farmer_county', models.TextField()),
                ('farmer_phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
