# Generated by Django 5.1.1 on 2024-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_remove_farmer_id_alter_farmer_farmer_county_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="farmer_id",
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
