# Generated by Django 5.1.1 on 2024-10-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0004_alter_farmer_farmer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_status', models.CharField(max_length=20)),
                ('last_updated', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='farmer.farmer')),
            ],
        ),
    ]
