# Generated by Django 5.1.1 on 2024-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_date', models.DateField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('affected_area_percentage', models.FloatField()),
            ],
        ),
    ]
