# Generated by Django 5.1.2 on 2024-10-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('pestincident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestincident',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='pestincident',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
        migrations.AddField(
            model_name='pestincident',
            name='leaf_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
