# Generated by Django 5.1.2 on 2024-10-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestincident', '0002_remove_pestincident_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestincident',
            name='leaf_status',
            field=models.CharField(max_length=20),
        ),
    ]
