# Generated by Django 5.1.2 on 2024-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestincident', '0004_remove_pestincident_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestincident',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
