# Generated by Django 5.1.2 on 2024-10-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pestincident', '0005_pestincident_confidence_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestincident',
            name='confidence_score',
        ),
    ]
