# Generated by Django 5.1.2 on 2024-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestincident', '0006_remove_pestincident_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestincident',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
    ]
