# Generated by Django 5.1.2 on 2024-10-22 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestincident', '0007_pestincident_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestincident',
            name='affected_area_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pestincident',
            name='confidence_score',
            field=models.FloatField(),
        ),
    ]
