# Generated by Django 5.1.2 on 2024-10-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pestincident', '0008_alter_pestincident_affected_area_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestincident',
            name='confidence_score',
        ),
    ]
